#if IRIS_TAG_SUPPORT >= 2
# Water
block.8=minecraft:water
# Full foliage
block.18=%minecraft:leaves minecraft:vine minecraft:cave_vines minecraft:cave_vines_plant minecraft:weeping_vines minecraft:weeping_vines_plant minecraft:twisting_vines minecraft:twisting_vines_plant
# Non-waving plant material
block.6=%minecraft:saplings
block.39=minecraft:brown_mushroom minecraft:red_mushroom
block.83=minecraft:sugar_cane
block.104=minecraft:pumpkin_stem minecraft:attached_pumpkin_stem minecraft:melon_stem minecraft:attached_melon_stem
block.115=minecraft:nether_wart
# Low vegetation
block.31=%minecraft:flowers minecraft:wheat minecraft:carrots minecraft:potatoes minecraft:beetroots minecraft:torchflower_crop minecraft:pitcher_crop minecraft:short_grass minecraft:tall_grass minecraft:short_dry_grass minecraft:tall_dry_grass minecraft:fern minecraft:large_fern minecraft:dead_bush minecraft:seagrass minecraft:tall_seagrass minecraft:sea_pickle minecraft:bush minecraft:firefly_bush
#else
# Water
block.8=minecraft:water
# Full foliage
block.18=minecraft:oak_leaves minecraft:spruce_leaves minecraft:birch_leaves minecraft:jungle_leaves minecraft:acacia_leaves minecraft:dark_oak_leaves minecraft:mangrove_leaves minecraft:cherry_leaves minecraft:azalea_leaves minecraft:flowering_azalea_leaves minecraft:pale_oak_leaves minecraft:vine minecraft:cave_vines minecraft:cave_vines_plant minecraft:weeping_vines minecraft:weeping_vines_plant minecraft:twisting_vines minecraft:twisting_vines_plant
# Non-waving plant material
block.6=minecraft:oak_sapling minecraft:spruce_sapling minecraft:birch_sapling minecraft:jungle_sapling minecraft:acacia_sapling minecraft:dark_oak_sapling minecraft:mangrove_propagule minecraft:cherry_sapling minecraft:pale_oak_sapling minecraft:azalea minecraft:flowering_azalea
block.39=minecraft:brown_mushroom minecraft:red_mushroom
block.83=minecraft:sugar_cane
block.104=minecraft:pumpkin_stem minecraft:attached_pumpkin_stem minecraft:melon_stem minecraft:attached_melon_stem
block.115=minecraft:nether_wart
# Low vegetation
block.31=minecraft:dandelion minecraft:golden_dandelion minecraft:poppy minecraft:blue_orchid minecraft:allium minecraft:azure_bluet minecraft:red_tulip minecraft:orange_tulip minecraft:white_tulip minecraft:pink_tulip minecraft:oxeye_daisy minecraft:cornflower minecraft:lily_of_the_valley minecraft:wither_rose minecraft:open_eyeblossom minecraft:closed_eyeblossom minecraft:sunflower minecraft:lilac minecraft:rose_bush minecraft:peony minecraft:torchflower minecraft:pitcher_plant minecraft:pink_petals minecraft:wildflowers minecraft:mangrove_propagule minecraft:chorus_flower minecraft:spore_blossom minecraft:cactus_flower minecraft:flowering_azalea minecraft:wheat minecraft:carrots minecraft:potatoes minecraft:beetroots minecraft:torchflower_crop minecraft:pitcher_crop minecraft:short_grass minecraft:tall_grass minecraft:short_dry_grass minecraft:tall_dry_grass minecraft:fern minecraft:large_fern minecraft:dead_bush minecraft:seagrass minecraft:tall_seagrass minecraft:sea_pickle minecraft:bush minecraft:firefly_bush
#endif